// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const blacklistToken = `-- name: BlacklistToken :one
INSERT INTO jwt_blacklist (
    token_id,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3
)
ON CONFLICT (token_id) DO NOTHING
RETURNING id, token_id, user_id, revoked_at, expires_at
`

type BlacklistTokenParams struct {
	TokenID   string        `json:"token_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) BlacklistToken(ctx context.Context, arg BlacklistTokenParams) (JwtBlacklist, error) {
	row := q.db.QueryRowContext(ctx, blacklistToken, arg.TokenID, arg.UserID, arg.ExpiresAt)
	var i JwtBlacklist
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.UserID,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const cleanupExpiredBlacklistTokens = `-- name: CleanupExpiredBlacklistTokens :exec
DELETE FROM jwt_blacklist
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredBlacklistTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredBlacklistTokens)
	return err
}

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < CURRENT_TIMESTAMP OR (revoked_at IS NOT NULL AND revoked_at < CURRENT_TIMESTAMP - INTERVAL '7 days')
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredTokens)
	return err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_id,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token_id, expires_at, created_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenID   string    `json:"token_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.TokenID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token, expires_at, created_at, used_at FROM email_verification_tokens
WHERE token = $1 AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, created_at, used_at FROM password_reset_tokens
WHERE token = $1 AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_id, expires_at, created_at, revoked_at FROM refresh_tokens
WHERE token_id = $1 AND revoked_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenID string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const isTokenBlacklisted = `-- name: IsTokenBlacklisted :one
SELECT COUNT(*) > 0 as blacklisted FROM jwt_blacklist
WHERE token_id = $1 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) IsTokenBlacklisted(ctx context.Context, tokenID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTokenBlacklisted, tokenID)
	var blacklisted bool
	err := row.Scan(&blacklisted)
	return blacklisted, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :one
UPDATE email_verification_tokens
SET
    used_at = CURRENT_TIMESTAMP
WHERE token = $1 AND used_at IS NULL
RETURNING id, user_id, token, expires_at, created_at, used_at
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, markEmailVerificationTokenUsed, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :one
UPDATE password_reset_tokens
SET
    used_at = CURRENT_TIMESTAMP
WHERE token = $1 AND used_at IS NULL
RETURNING id, user_id, token, expires_at, created_at, used_at
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, markPasswordResetTokenUsed, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET
    revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

// Revoke refresh tokens
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET
    revoked_at = CURRENT_TIMESTAMP
WHERE token_id = $1 AND revoked_at IS NULL
RETURNING id, user_id, token_id, expires_at, created_at, revoked_at
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenID string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
