// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailVerificationToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type JwtBlacklist struct {
	ID        uuid.UUID     `json:"id"`
	TokenID   string        `json:"token_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	RevokedAt sql.NullTime  `json:"revoked_at"`
	ExpiresAt time.Time     `json:"expires_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdatedBy   uuid.NullUUID  `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenID   string       `json:"token_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdatedBy   uuid.NullUUID  `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type RolePermission struct {
	ID           uuid.UUID     `json:"id"`
	RoleID       uuid.UUID     `json:"role_id"`
	PermissionID uuid.UUID     `json:"permission_id"`
	AssignedBy   uuid.NullUUID `json:"assigned_by"`
	AssignedAt   sql.NullTime  `json:"assigned_at"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Username            string         `json:"username"`
	Email               string         `json:"email"`
	PasswordHash        string         `json:"password_hash"`
	FullName            sql.NullString `json:"full_name"`
	IsDisabled          sql.NullBool   `json:"is_disabled"`
	IsEmailVerified     sql.NullBool   `json:"is_email_verified"`
	FailedLoginAttempts sql.NullInt32  `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime   `json:"locked_until"`
	LastLoginAt         sql.NullTime   `json:"last_login_at"`
	CreatedBy           uuid.NullUUID  `json:"created_by"`
	UpdatedBy           uuid.NullUUID  `json:"updated_by"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type UserRole struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
	AssignedAt sql.NullTime  `json:"assigned_at"`
}
